//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        public string ItemOID { get; set; }
        public string ContentID { get; set; }
        public string Museum { get; set; }
        public string FunctionOID { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string EntryUrl { get; set; }
        public string Bit { get; set; }
        public int ClickCount { get; set; }
        public Nullable<bool> CoverImage { get; set; }
        public int State { get; set; }
        public string StateMessage { get; set; }
        public int Sort { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Content Content { get; set; }
    }
}
