//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Introduction
    {
        public string ID { get; set; }
        public string MuseumName { get; set; }
        public string Museum { get; set; }
        public string Description { get; set; }
        public string OpenTimeIntro { get; set; }
        public string Address { get; set; }
        public string Traffic { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CoverImage { get; set; }
        public bool IsOuterCoverImage { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Ticket { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsPublish { get; set; }
    }
}
